- name: Ensure the system can use the HTTPS transport for APT.
  stat:
    path: /usr/lib/apt/methods/https
  register: apt_https_transport

- name: stop and disable tomcat
  service:
    daemon_reload: yes
    name: tomcat
    state: stopped
    enabled: no
  when: ansible_service_mgr == "systemd"
  ignore_errors: yes

- name: Remove APT HTTPS transport.
  apt:
    name: "apt-transport-https"
    state: absent
    update_cache: yes
  when: not apt_https_transport.stat.exists

- name: Remove basic packages
  package:
    name: ['vim','aptitude','bash-completion','tree','htop','wget','unzip','curl','git']
    state: absent

- name: Remove Default Java (Debian/Ubuntu)
  apt:
    name: default-jdk
    state: absent


- name: Remove "tomcat" user
  user:
    name: tomcat
    state: absent

# - name: Download Tomcat
#   get_url:
#     url: "{{ tomcat_archive_url }}"
#     dest: "{{ tomcat_archive_dest }}"

- name: remove tomcat directory
  file:
    path: "{{ tomcat_archive_dest }}"
    state: absent

- name: Remove a tomcat directory
  file:
    path: "{{ item }}"
    state: absent
  with_items:
    - /usr/share/tomcat
    - /etc/systemd/system/tomcat.service



# - name: Extract tomcat archive
#   unarchive:
#     src: "{{ tomcat_archive_dest }}"
#     dest: /usr/share/tomcat
#     owner: tomcat
#     group: tomcat
#     remote_src: yes
#     extra_opts: "--strip-components=1"
#     Removes: /usr/share/tomcat/bin

# - name: Copy tomcat service file
#   template:
#     src: templates/tomcat.service.j2
#     dest: /etc/systemd/system/tomcat.service
#   when: ansible_service_mgr == "systemd"

# - name: Start and enable tomcat
#   service:
#     daemon_reload: yes
#     name: tomcat
#     state: started
#     enabled: yes
#   when: ansible_service_mgr == "systemd"

# - name: Set UI access credentials
#   template:
#     src: tomcat-users.xml.j2
#     dest: /usr/share/tomcat/conf/tomcat-users.xml
#   notify: restart tomcat

# - name: Allow access to Manager and Host Manager apps from any IP
#   template:
#     src: context.xml.j2 
#     dest: "{{ item }}"
#   with_items:
#     - /usr/share/tomcat/webapps/host-manager/META-INF/context.xml
#     - /usr/share/tomcat/webapps/manager/META-INF/context.xml
#   notify: restart tomcat

