---
- name: Health Check create
  copy:
    dest: /tmp/hc.sh
    mode: 0777
    content: |
       #!/bin/sh
       free -m | awk 'NR==2{printf "Memory Usage: %s/%sMB (%.2f%%)\n", $3,$2,$3*100/$2 }'
       df -h | awk '$NF=="/"{printf "Disk Usage: %d/%dGB (%s)\n", $3,$2,$5}'
       top -bn1 | grep load | awk '{printf "CPU Load: %.2f\n", $(NF-2)}'
       echo "Uptime: $(uptime)" 

- name: Health_check run
  shell: /tmp/hc.sh
  register: ps

- name: output ps
  debug: var=ps.stdout_lines